version: '3.8'

services:

  mfa-service:
    image: mfa-service:latest
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /data/mfa-service
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/mfa-service?allowPublicKeyRetrieval=true
      - spring.liquibase.url=jdbc:mysql://mysql:3306/mfa-service?allowPublicKeyRetrieval=true

    depends_on:
      - mysql

  mysql:
    image: mysql:8.1
    command: --lower_case_table_names=1
    volumes:
      - ./mysql-volume:/var/lib/mysql --user 1000
    environment:
      MYSQL_DATABASE: "mfa-service"
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    networks:
      - springapimysql-net
    expose:
      - '3306'

networks:
  springapimysql-net:
