server:
    port : 8088
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/mfa-service?autoReconnect=true&useSSL=false&serverTimezone=Europe/Berlin
    liquibase:
        url: jdbc:mysql://127.0.0.1:3306/mfa-service?autoReconnect=true&createDatabaseIfNotExist=true&serverTimezone=Europe/Berlin